import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/ui/Footer'
import NavBarHeader from './components/ui/NavBarHeader'
import Animation from './components/ui/Animation'
import CustomCursor from './components/animations/CustomCursor'
import { Providers } from './providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ignytes Solution',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     
        <CustomCursor/>
        <Animation/>
      <NavBarHeader/>
      
        {children}
        <Footer/>
      

        </body>
    </html>
  )
}
